### ISSUE TITLE
Milestone 1: Individual Contribution Report - Halil Ibrahim Gürbüz

### ISSUE THREAD

**Issue by halilgurbuz** [bounswe/bounswe2023group2#116]
### Issue Description

I will prepare my individual report and my part of the RAM.

Parts of the task:
- [x] Write the individual report
- [x] Add it to GitHub
- [x] Add it to Milestone 1 Report

### Deadline of the Issue

10.04.2023 23.59

### Reviewer

Halil Ibrahim Gürbüz
