### ISSUE TITLE
Milestone 1: Individual Contribution Report - Mehmet Emin İpekdal

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#127]
### Issue Description

Each member will prepare their own separate page using markdown and add the link to their page under the ‘Individual Contribution Reports’ section of your milestone report. While preparing your individual reports, provide the necessary hyperlinks and references to your work in your project repository.

Your individual milestone should be structured as follows:
- [x] Member: Info about myself (name, group)
- [x] Responsibilities: Overall description of the responsibilities that are assigned to me
- [x] Main contributions: Overall description of my contributions to the project until Milestone. Provide the links to your work and related issues in your project repository. 
- [x] Management related significant issues: My issues that contribute to the management of our software project (Please only lists the most-significant ones, we DO track all your issues separately.)
- [x] Additional information (optional): Further relevant information related to my contributions

Personal contributions to your project repositories (Wiki, issues), communication, and meetings impact your individual assessment. The coherence with and the benefit to group performance is of high significance. Good group work calls for quality individual contributions as well as assistance of each other. The qualities of good issues, commits, and pull/merge requests have been covered and reiterated numerous times. They are expected to be well written and appropriately closed (with links to relevant outcomes).

### Deadline of the Issue

10.04.2023

### Reviewer

Hasan Bingölbali

**Comment by rburaksaritas** [comment]
Closing the issue since @mehmeteminipekdal  completed the report as described.
