### ISSUE TITLE
Create MileStone 2 Report

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#195]
### Issue Description

Milestone report should be prepared using markdown and include at least the following:

Executive Summary:
– Summary of project and overall status
– Description of the basic functionality of your project (can include screen shots)
URL of practice app code and the tag
– URL of your application that was deployed with docker
Any information we may need to test your application
Instructions for building the application with docker.
– API URL (the URL should take us to a documented API)
Links to meeting notes related to practice app
Lessons learned: evaluation of tools and processes utilized to manage the team project.
– Challenges you met as a group
A section summarizing member contributions. A subsection will be created for each team member that summarizes their contributions (each team member must write their own section). The subsections should be organized in alphabetical order by surnames of members. Each member section will provide:
- Their own name (as section name)
- Links to important issues (git issues) and wiki documentation related to practice application
- The name, route, description of utilized third party URIs
- The name, route, description of the created API functions
- Description of unit tests. You can include code fragments to illustrate.
- Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- Any other significant work related to this release (such as Docker, AWS, DB, Framework)
- Describe any challenges you met during implementation.

- [x] #197
- [x] #198
- [x] #199
- [x] #200
- [x] #201
- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208

### Deadline of the Issue

12.05.23

### Reviewer

Egecan Serbester

**Comment by bgmrsln** [comment]
- [ ] Write Executive Summary
- [ ] Write member contribution - Aras
- [ ] Write member contribution - Begüm
- [ ] Write member contribution - Cahid
- [ ] Write member contribution - Egecan
- [ ] Write member contribution - Halil
- [ ] Write member contribution - Hasan
- [ ] Write member contribution - Mehmet Emin
- [ ] Write member contribution - Mehmet K.
- [ ] Write member contribution - Merve
- [ ] Write member contribution -Şahin
- [ ] Write member contribution - Burak

**Comment by bgmrsln** [comment]
With the written executive summary, this issue is also closed.
