### ISSUE TITLE
Implementation of Project Plan to the Github Roadmap

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#304]
### Issue Description

As the members of the each subteam, we need to build the project plan and show it on github roadmap. 

- [ ] List the tasks from requirements
- [ ] Divide into 3 milestones
- [ ] Add start and due times
- [ ] Assign people

### Deadline of the Issue

12.10.2023

### Reviewer

Egecan Serbester

**Comment by egecans** [comment]
for Mobile: I list tasks from requirements, then divide them into 3 mileStones after that arranged start and due times and assigned members of the mobile team.

**Comment by mervegrbz** [comment]
Recently we have done:
- classify tasks in terms of backend, frontend and mobile.
- Divide the tasks into 3 milestones.
I am closing the issue, since it is done apart from casual fixes
